flowchart LR
  U[Usuario] --> F[Front Web]
  F --> G[Gateway Service :3000]
  G --> C[Orchestrator Service :3001]
  C --> K[Knowledge Base Service :3002]
  C --> E[External API Service :3003 MCP Server]
  C --> X[Explanation Service :3004]
  K --> C
  E --> C
  X --> C
  C --> G
  G --> F
  F --> U

  subgraph SAGA[Maintenance Saga]
    S1[Start Reindex]
    S2[Start Cache Snapshot]
    S3[Commit or Rollback]
  end

  C -. inicia .-> S1
  C -. inicia .-> S2
  S1 -. publica/compensa .-> K
  S2 -. publica/compensa .-> E
  S1 -. valida .-> S3
  S2 -. valida .-> S3

  subgraph RAG
    K --> V[Vector Store Snapshot]
    V --> M[all-MiniLM-L6-v2]
    M --> D[Documentos F1 chunked]
  end

  subgraph MCP
    E --> T[Tools RapidAPI F1 + cache snapshot]
  end

  subgraph LLM
    X --> L[Groq API llama3-70b]
  end
